#!/bin/bash
set -euo pipefail

# install-workflow.sh
# Installs a GitHub Actions workflow that generates a daily worklog report
# and publishes it to the repository's private wiki.
#
# Usage:
#   ./scripts/install-workflow.sh
#
# Prerequisites:
#   - gh CLI installed and authenticated (https://cli.github.com/)
#   - Working directory must be inside a git repo tracked on GitHub

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

WORKFLOW_DIR="$REPO_ROOT/.github/workflows"
WORKFLOW_FILE="$WORKFLOW_DIR/wrklogr-daily.yaml"

echo "🔧 Installing wrklogr daily workflow..."

# ---- checks ----

if ! command -v gh &>/dev/null; then
  echo "❌ gh CLI is required but not found."
  echo "   Install it from https://cli.github.com/"
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo "❌ gh CLI is not authenticated."
  echo "   Run 'gh auth login' first."
  exit 1
fi

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo "❌ Not inside a git repository."
  exit 1
fi

# ---- derive repo info ----
REMOTE=$(git config --get remote.origin.url || true)
if [[ -z "$REMOTE" ]]; then
  echo "❌ No remote 'origin' found."
  exit 1
fi

# Normalise SSH and HTTPS remote URLs to owner/repo
OWNER_REPO=$(echo "$REMOTE" \
  | sed -n 's|.*github.com[:/]\(.*\)\.git|\1|p' \
  | sed -n 's|.*github.com[:/]\(.*\)|\1|p')
if [[ -z "$OWNER_REPO" ]]; then
  echo "❌ Could not parse owner/repo from remote '$REMOTE'."
  exit 1
fi

OWNER="${OWNER_REPO%/*}"
REPO="${OWNER_REPO#*/}"

# ---- create workflow dir ----
mkdir -p "$WORKFLOW_DIR"

# ---- write workflow file ----
cat > "$WORKFLOW_FILE" << 'WORKFLOW'
# wrklogr-daily.yaml
# Generates a daily worklog report and publishes it to the repository's wiki.
#
# How it works:
#   1. Builds wrklogr from source
#   2. Generates a report for yesterday via GitHub API (--me flag)
#   3. Pushes the report as a new wiki page
#
# Required setup:
#   - Enable the wiki: repository Settings > Features > Wikis
#   - wrklogr.toml must list the repos to scan
#   - For cross-org repos, create a fine-grained PAT with "Contents: Read"
#     on those repos and save it as the WORKLOG_TOKEN secret.

name: Daily Worklog

on:
  schedule:
    # Run at 23:59 UTC every day (end of day)
    - cron: "59 23 * * *"
  workflow_dispatch:
    inputs:
      since:
        description: "Start date (YYYY-MM-DD)"
        required: false
        default: ""
      until:
        description: "End date (YYYY-MM-DD)"
        required: false
        default: ""

env:
  GO_VERSION: "1.22"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push to the wiki (separate ref)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: wrklogr

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: wrklogr/go.sum

      - name: Build wrklogr
        working-directory: wrklogr
        run: go build -o /tmp/wrklogr cmd/wrklogr/main.go

      - name: Generate report
        id: report
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.WORKLOG_TOKEN || secrets.GITHUB_TOKEN }}
        working-directory: wrklogr
        run: |
          YESTERDAY=$(date -u -d 'yesterday' '+%Y-%m-%d')
          echo "report_date=${YESTERDAY}" >> "${GITHUB_OUTPUT}"

          SINCE="${YESTERDAY}"
          UNTIL="${YESTERDAY}"

          if [ -n "${{ inputs.since }}" ]; then
            SINCE="${{ inputs.since }}"
            UNTIL="${{ inputs.until }}"
          fi

          /tmp/wrklogr report \
            --since "${SINCE}" \
            --until "${UNTIL}" \
            --local=false \
            --me \
            2>&1 | tee /tmp/wrklogr-output.txt

          echo "${YESTERDAY}" > /tmp/wrklogr-date.txt
          echo "https://github.com/${{ github.repository }}" > /tmp/wrklogr-repo.txt

      - name: Prepare wiki page
        shell: bash
        run: |
          REPORT_DATE=$(cat /tmp/wrklogr-date.txt)
          REPO_URL=$(cat /tmp/wrklogr-repo.txt)
          NOW_UTC=$(date -u '+%Y-%m-%d %H:%M UTC')

          # Build wiki page from the report output.
          # Use printf to avoid any shell interpretation of the report
          # content (backticks, $, etc. in the report are literal).
          {
            printf '# Worklog Report\n\n'
            printf '## %s\n\n' "${REPORT_DATE}"
            printf '```\n'
            cat /tmp/wrklogr-output.txt
            printf '\n```\n\n'
            printf '---\n'
            printf '_Generated by [wrklogr](%s) on %s_\n' "${REPO_URL}" "${NOW_UTC}"
          } > /tmp/wiki-page.md

      - name: Push to wiki
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.WORKLOG_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          REPORT_DATE="${{ steps.report.outputs.report_date }}"
          PAGE="worklog-${REPORT_DATE}"
          OWNER="${{ github.repository_owner }}"
          REPO="${GITHUB_REPOSITORY#*/}"

          # Shallow clone the wiki repo using the token
          git clone \
            "https://x-access-token:${GH_TOKEN}@github.com/${OWNER}/${REPO}.wiki.git" \
            /tmp/wiki \
            --depth 1

          cd /tmp/wiki

          git config user.name  "wrklogr-bot"
          git config user.email "wrklogr-bot@users.noreply.github.com"

          # Write the new page
          cp /tmp/wiki-page.md "${PAGE}.md"
          git add "${PAGE}.md"

          # Maintain an index page
          if [ ! -f "worklogs.md" ]; then
            printf '# Worklogs\n\nDaily reports generated by [wrklogr](https://github.com/%s/%s).\n\n' \
              "${OWNER}" "${REPO}" > worklogs.md
          fi

          # Insert/replace the link for this date
          if grep -q "^\- \[${REPORT_DATE}\]" worklogs.md 2>/dev/null; then
            sed -i "s|^\- \[${REPORT_DATE}\].*|- [${REPORT_DATE}](./${PAGE})|" worklogs.md
          else
            # Insert after the first blank line (top of the list)
            sed -i '0,/^$/ s|^$|- ['"${REPORT_DATE}"'](./'"${PAGE}"')\n|' worklogs.md
          fi
          git add worklogs.md

          git commit -m "Add worklog report for ${REPORT_DATE}"
          git push
WORKFLOW

echo "✅ Workflow created at: $WORKFLOW_FILE"
echo ""
echo "─── Next steps ──────────────────────────────────────────────"
echo ""
echo "  1. Make sure wrklogr.toml lists all the repos you want to"
echo "     scan (uses GitHub API mode)."
echo ""
echo "  2. If you need to scan repos outside this one, create a"
echo "     fine-grained Personal Access Token (PAT) with"
echo "     'Contents: Read' on each target repo and save it as:"
echo ""
echo "       https://github.com/${OWNER}/${REPO}/settings/secrets/actions"
echo ""
echo "     Secret name: WORKLOG_TOKEN"
echo ""
echo "     Otherwise the built-in GITHUB_TOKEN only grants access to"
echo "     ${OWNER}/${REPO}."
echo ""
echo "  3. Enable the repo wiki if it's off:"
echo ""
echo "       https://github.com/${OWNER}/${REPO}/settings"
echo ""
echo "  4. Commit and push the workflow:"
echo ""
echo "       git add .github/workflows/"
echo "       git commit -m \"ci: add daily worklog workflow\""
echo "       git push"
echo ""
echo "  5. Test it manually:"
echo ""
echo "       gh workflow run wrklogr-daily.yaml"
